version: "3"
services:
  postgres:
    image: "postgres:11-alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
volumes:
  postgres-vol: